import React from "react";
import { Link } from "react-router-dom";
import logo from "../assets/logo.png"
import { BarChart, BotIcon, ChartArea, CogIcon, Handshake, LayoutDashboard, LayoutGrid, LockIcon, MessageCircle, Notebook, Palette, Paperclip, Pencil, Rocket, Target, Wrench, Zap, ZapIcon } from "lucide-react";
 
const roles = [
  { emoji: <Palette/>, name: "Frontend Developer", desc: "HTML, CSS, JS, React, performance" },
  { emoji:<CogIcon/>, name: "Backend Developer",  desc: "APIs, databases, servers, architecture" },
  { emoji: <Rocket/>, name: "Full Stack Developer", desc: "End-to-end systems and integration" },
  { emoji: <LayoutGrid/>, name: "Data Scientist",     desc: "ML, statistics, Python, data pipelines" },
  { emoji: <Wrench/>, name: "DevOps Engineer",    desc: "CI/CD, cloud, containers, monitoring" },
  { emoji:<Handshake/> , name: "HR / Behavioral",    desc: "Soft skills, culture fit, situational" },
  { emoji: <Notebook/>, name: "Product Manager",    desc: "Roadmapping, metrics, stakeholders" },
  { emoji: <Pencil/>, name: "UI/UX Designer",     desc: "Design systems, UX research, Figma" },
];
 
const features = [
  { icon: <BotIcon/>, bg: "#6c63ff22", title: "AI-Tailored Questions",   desc: "Every question is dynamically generated by GPT-4o for your exact role — no recycled question banks." },
  { icon: <ZapIcon/>, bg: "#38bdf822", title: "Instant Expert Feedback",  desc: "Get detailed feedback and a score out of 10 on each answer within seconds of submitting." },
  { icon: <Paperclip/>, bg: "#4ade8018", title: "Resume-Aware (Optional)", desc: "Upload your PDF resume and the AI generates questions tailored to your actual experience and skills." },
  { icon: <BarChart/>, bg: "#6c63ff22", title: "Progress Dashboard",       desc: "Track all your past mock interviews, see score trends, and identify areas to improve." },
  { icon: <Target/>, bg: "#38bdf822", title: "Role-Specific Depth",      desc: "Questions adapt to the technical depth of each role — from coding concepts to leadership scenarios." },
  { icon:<LockIcon/> , bg: "#4ade8018", title: "Private & Secure",         desc: "Your answers and scores are private to your account. Practice with complete confidence." },
];
 
const stats = [
  { num: "8",      label: "Roles" },
  { num: "5",      label: "Questions each" },
  { num: "GPT-4o", label: "AI Model" },
  { num: <ZapIcon/>,     label: "Instant feedback" },
];
 
export default function LandingPage() {
  return (
    <div style={s.page}>
      <style>{css}</style>
 
      {/* ── NAV ─────────────────────────────────── */}
      <nav style={s.nav}>
        <div style={s.logo}>
          <div style={s.logoIcon}><img
  src={logo}
  alt="Brand Logo"
  style={{
    width: "40px",
    height: "40px",
    display: "inline-block",
    objectFit: "contain",
  }}
/></div>
          MockVerse
        </div>
        <div style={s.navLinks}>
          <a href="#how"      style={s.navLink}>How it works</a>
          <a href="#roles"    style={s.navLink}>Roles</a>
          <a href="#features" style={s.navLink}>Features</a>
          <Link to="/register" style={s.navCta}>Get Started</Link>
        </div>
      </nav>
 
      {/* ── HERO ────────────────────────────────── */}
      <section style={s.hero}>
        <div style={s.heroGlow} />
        <div style={s.heroGlow2} />
 
        <div style={s.badge}>
          <span style={s.badgeDot} className="pulse" />
          ✦ Powered by GPT-4o-mini
        </div>
 
        <h1 style={s.h1} className="animate-fadeInUp">
          Ace Your Next<br />
          <span style={{ color: "#6c63ff" }}>Interview</span>{" "}
          with <span style={{ color: "#38bdf8" }}>AI</span>
        </h1>
 
        <p style={s.heroSub} className="animate-fadeInUp delay-1">
          Get AI-generated questions tailored to your role, answer at your own pace,
          and receive instant expert feedback with a score out of 10.
        </p>
 
        <div style={s.heroActions} className="animate-fadeInUp delay-2">
          <Link to="/register" style={s.btnPrimary} className="btn-primary-hover">
            Start Practicing Free →
          </Link>
          <a href="#how" style={s.btnSecondary} className="btn-secondary-hover">
            See how it works
          </a>
        </div>
 
        <div style={s.statsRow} className="animate-fadeInUp delay-3">
          {stats.map((st) => (
            <div key={st.label} style={s.stat}>
              <span style={s.statNum}>{st.num}</span>
              <span style={s.statLabel}>{st.label}</span>
            </div>
          ))}
        </div>
 
        <div style={s.scrollHint}>
          <div className="scroll-arrow" />
        </div>
      </section>
 
      {/* ── HOW IT WORKS ────────────────────────── */}
      <section id="how" style={s.section}>
        <p style={s.sectionLabel}>Process</p>
        <h2 style={s.h2}>Three steps to interview mastery</h2>
        <p style={s.sectionSub}>From choosing your role to getting actionable feedback — in minutes.</p>
 
        <div style={s.stepsGrid}>
          {[
            { num: "01", icon: <Target/>, title: "Pick Your Role",     desc: "Choose from 8 tech and non-tech roles, from Frontend Dev to Product Manager." },
            { num: "02", icon: <MessageCircle/>, title: "Answer Questions",   desc: "Receive 5 AI-generated, role-specific interview questions and type your answers at your own pace." },
            { num: "03", icon: <LayoutDashboard/>, title: "Get Scored",         desc: "Receive instant expert-level feedback with a score out of 10 and suggestions to improve." },
            { num: "04", icon:<Rocket/>, title: "Track Progress",     desc: "Review past sessions on your dashboard and measure how you improve over time." },
          ].map((step) => (
            <div key={step.num} style={s.stepCard} className="step-card">
              <span style={s.stepNum}>{step.num}</span>
              <div style={s.stepIcon}>{step.icon}</div>
              <h3 style={s.stepTitle}>{step.title}</h3>
              <p style={s.stepDesc}>{step.desc}</p>
            </div>
          ))}
        </div>
      </section>
 
      {/* ── ROLES ───────────────────────────────── */}
      <section id="roles" style={{ ...s.section, background: "#0f1120" }}>
        <p style={s.sectionLabel}>Interview Roles</p>
        <h2 style={s.h2}>Pick your target position</h2>
        <p style={s.sectionSub}>We generate questions tailored specifically to each role's unique demands.</p>
 
        <div style={s.rolesGrid}>
          {roles.map((r) => (
            <div key={r.name} style={s.roleCard} className="role-card">
              <span style={{ fontSize: "2rem" }}>{r.emoji}</span>
              <span style={s.roleName}>{r.name}</span>
              <span style={s.roleDesc}>{r.desc}</span>
            </div>
          ))}
        </div>
      </section>
 
      {/* ── FEATURES ────────────────────────────── */}
      <section id="features" style={s.section}>
        <p style={s.sectionLabel}>Features</p>
        <h2 style={s.h2}>Everything you need to prepare</h2>
        <p style={s.sectionSub}>A complete interview prep toolkit powered by cutting-edge AI.</p>
 
        <div style={s.featuresGrid}>
          {features.map((f) => (
            <div key={f.title} style={s.featureCard} className="feature-card">
              <div style={{ ...s.featureIcon, background: f.bg }}>{f.icon}</div>
              <h3 style={s.featureTitle}>{f.title}</h3>
              <p style={s.featureDesc}>{f.desc}</p>
            </div>
          ))}
        </div>
      </section>
 
      {/* ── CTA ─────────────────────────────────── */}
      <section style={{ ...s.section, background: "#0f1120", textAlign: "center" }}>
        <div style={s.ctaCard}>
          <div style={s.ctaGlow} />
          <h2 style={{ ...s.h2, marginBottom: "1rem" }}>Ready to ace your interview?</h2>
          <p style={{ color: "#7a7e9a", marginBottom: "2rem" }}>
            Join thousands of candidates who practice smarter with AiMock.
          </p>
          <Link to="/register" style={s.btnPrimary} className="btn-primary-hover">
            Create Free Account →
          </Link>
        </div>
      </section>
 
      {/* ── FOOTER ──────────────────────────────── */}
      <footer style={s.footer}>
        <div style={s.logo}>
          <img
            src={logo}
            alt="MockVerse Logo"
            style={{
              width: "30px",
              height: "30px",
              display: "inline-block",
              objectFit: "contain",
            }}
          />
          MockVerse
        </div>
        <div style={{ display: "flex", gap: "1.5rem" }}>
          {["Privacy", "Terms", "Contact"].map((l) => (
            <a key={l} href="#" style={s.footerLink}>{l}</a>
          ))}
        </div>
        <span style={{ color: "#7a7e9a", fontSize: "0.85rem" }}>© 2026 MockVerse. All rights reserved.</span>
      </footer>
    </div>
  );
}
 
/* ── Styles ───────────────────────────────────────────────────────────────── */
const s = {
  page:        { background: "#0a0b14", color: "#e8e9f3", fontFamily: "'DM Sans', sans-serif", minHeight: "100vh", overflowX: "hidden" },
  nav:         { position: "fixed", top: 0, left: 0, right: 0, zIndex: 100, display: "flex", alignItems: "center", justifyContent: "space-between", padding: "1rem 3rem", background: "rgba(10,11,20,0.85)", backdropFilter: "blur(16px)", borderBottom: "1px solid rgba(255,255,255,0.07)" },
  logo: {
  display: "flex",
  alignItems: "center",
  gap: 10,
  fontFamily: "'Syne', sans-serif",
  fontSize: "1.3rem",
  fontWeight: 700,
  color: "#e8e9f3",
  textDecoration: "none"
},

logoIcon: {
  width: 34,
  height: 34,
  borderRadius: 10,
  
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  fontSize: 18,
  fontWeight: 800,
  color: "white",
  // boxShadow: "0 4px 15px rgba(108,99,255,0.4)"
},
  navLinks:    { display: "flex", alignItems: "center", gap: "2rem" },
  navLink:     { color: "#7a7e9a", fontSize: "0.9rem", textDecoration: "none" },
  navCta:      { background: "#6c63ff", color: "#fff", padding: "0.5rem 1.2rem", borderRadius: 8, fontSize: "0.9rem", fontWeight: 500, textDecoration: "none" },
 
  hero:        { minHeight: "100vh", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", padding: "8rem 2rem 4rem", textAlign: "center", position: "relative", overflow: "hidden" },
  heroGlow:    { position: "absolute", top: -200, left: "50%", transform: "translateX(-50%)", width: 700, height: 700, background: "radial-gradient(ellipse at center,rgba(108,99,255,0.18) 0%,transparent 70%)", pointerEvents: "none" },
  heroGlow2:   { position: "absolute", bottom: -100, right: -150, width: 500, height: 500, background: "radial-gradient(ellipse at center,rgba(56,189,248,0.1) 0%,transparent 70%)", pointerEvents: "none" },
  badge:       { display: "inline-flex", alignItems: "center", gap: 6, background: "rgba(108,99,255,0.15)", border: "1px solid rgba(108,99,255,0.3)", color: "#a78bfa", padding: "6px 16px", borderRadius: 100, fontSize: "0.78rem", fontWeight: 500, letterSpacing: "0.08em", textTransform: "uppercase", marginBottom: "2rem" },
  badgeDot:    { width: 6, height: 6, borderRadius: "50%", background: "#a78bfa" },
  h1:          { fontFamily: "'Syne', sans-serif", fontSize: "clamp(2.8rem,6vw,5rem)", fontWeight: 800, lineHeight: 1.1, letterSpacing: "-0.02em", marginBottom: "1.5rem" },
  heroSub:     { maxWidth: 560, color: "#7a7e9a", fontSize: "1.1rem", lineHeight: 1.7, marginBottom: "2.5rem" },
  heroActions: { display: "flex", gap: "1rem", flexWrap: "wrap", justifyContent: "center", marginBottom: "4rem" },
  btnPrimary:  { background: "#6c63ff", color: "#fff", padding: "0.85rem 2rem", borderRadius: 10, fontSize: "1rem", fontWeight: 500, textDecoration: "none", border: "none", cursor: "pointer", boxShadow: "0 0 30px rgba(108,99,255,0.35)", display: "inline-block" },
  btnSecondary:{ background: "transparent", color: "#e8e9f3", padding: "0.85rem 2rem", borderRadius: 10, fontSize: "1rem", fontWeight: 500, textDecoration: "none", border: "1px solid rgba(255,255,255,0.07)", display: "inline-block" },
 
  statsRow:    { display: "flex", gap: "3rem", flexWrap: "wrap", justifyContent: "center" },
  stat:        { textAlign: "center" },
  statNum:     { display: "block", fontFamily: "'Syne', sans-serif", fontSize: "2rem", fontWeight: 800, color: "#a78bfa" },
  statLabel:   { fontSize: "0.78rem", color: "#7a7e9a", textTransform: "uppercase", letterSpacing: "0.1em" },
  scrollHint:  { position: "absolute", bottom: "2rem", display: "flex", flexDirection: "column", alignItems: "center", gap: 6, color: "#7a7e9a", fontSize: "0.75rem" },
 
  section:     { padding: "6rem 2rem", background: "#0a0b14" },
  sectionLabel:{ textAlign: "center", fontSize: "0.78rem", color: "#a78bfa", fontWeight: 500, textTransform: "uppercase", letterSpacing: "0.12em", marginBottom: "0.75rem" },
  h2:          { textAlign: "center", fontFamily: "'Syne', sans-serif", fontSize: "clamp(1.8rem,4vw,2.8rem)", fontWeight: 700, marginBottom: "1rem" },
  sectionSub:  { textAlign: "center", color: "#7a7e9a", maxWidth: 500, margin: "0 auto 3.5rem", fontSize: "1rem" },
 
  stepsGrid:   { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(220px,1fr))", gap: "1.5rem", maxWidth: 900, margin: "0 auto" },
  stepCard:    { background: "#181a2e", border: "1px solid rgba(255,255,255,0.07)", borderRadius: 16, padding: "2rem 1.5rem", position: "relative", overflow: "hidden" },
  stepNum:     { fontFamily: "'Syne', sans-serif", fontSize: "3rem", fontWeight: 800, color: "rgba(108,99,255,0.12)", position: "absolute", top: "1rem", right: "1.2rem", lineHeight: 1 },
  stepIcon:    { width: 44, height: 44, borderRadius: 12, background: "rgba(108,99,255,0.12)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "1.3rem", marginBottom: "1.2rem" },
  stepTitle:   { fontFamily: "'Syne', sans-serif", fontSize: "1.05rem", fontWeight: 600, marginBottom: "0.5rem" },
  stepDesc:    { fontSize: "0.9rem", color: "#7a7e9a", lineHeight: 1.6 },
 
  rolesGrid:   { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(180px,1fr))", gap: "1rem", maxWidth: 900, margin: "0 auto" },
  roleCard:    { background: "#181a2e", border: "1px solid rgba(255,255,255,0.07)", borderRadius: 14, padding: "1.5rem 1.2rem", display: "flex", flexDirection: "column", alignItems: "center", gap: "0.75rem", cursor: "pointer" },
  roleName:    { fontFamily: "'Syne', sans-serif", fontSize: "0.9rem", fontWeight: 600, textAlign: "center" },
  roleDesc:    { fontSize: "0.75rem", color: "#7a7e9a", textAlign: "center" },
 
  featuresGrid:{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(280px,1fr))", gap: "1.5rem", maxWidth: 960, margin: "0 auto" },
  featureCard: { background: "#181a2e", border: "1px solid rgba(255,255,255,0.07)", borderRadius: 16, padding: "2rem" },
  featureIcon: { width: 48, height: 48, borderRadius: 12, display: "flex", alignItems: "center", justifyContent: "center", fontSize: "1.5rem", marginBottom: "1.2rem" },
  featureTitle:{ fontFamily: "'Syne', sans-serif", fontSize: "1.05rem", fontWeight: 600, marginBottom: "0.5rem" },
  featureDesc: { fontSize: "0.9rem", color: "#7a7e9a", lineHeight: 1.6 },
 
  ctaCard:     { maxWidth: 700, margin: "0 auto", background: "linear-gradient(135deg,rgba(108,99,255,0.12),rgba(56,189,248,0.06))", border: "1px solid rgba(108,99,255,0.25)", borderRadius: 24, padding: "4rem 3rem", position: "relative", overflow: "hidden" },
  ctaGlow:     { position: "absolute", top: -100, left: "50%", transform: "translateX(-50%)", width: 400, height: 300, background: "radial-gradient(ellipse,rgba(108,99,255,0.2),transparent 70%)", pointerEvents: "none" },
 
  footer:      { borderTop: "1px solid rgba(255,255,255,0.07)", padding: "2rem 3rem", display: "flex", alignItems: "center", justifyContent: "space-between", flexWrap: "wrap", gap: "1rem" },
  footerLink:  { color: "#7a7e9a", textDecoration: "none", fontSize: "0.85rem" },
};
 
const css = `
  @import url('https://fonts.googleapis.com/css2?family=Syne:wght@400;600;700;800&family=DM+Sans:wght@300;400;500&display=swap');
  * { box-sizing: border-box; margin: 0; padding: 0; }
 
  .pulse { animation: pulse 2s infinite; }
  @keyframes pulse { 0%,100%{opacity:1;transform:scale(1)} 50%{opacity:0.5;transform:scale(0.8)} }
 
  .scroll-arrow { width: 20px; height: 20px; border-right: 1.5px solid #7a7e9a; border-bottom: 1.5px solid #7a7e9a; transform: rotate(45deg); animation: bounce 1.5s infinite; }
  @keyframes bounce { 0%,100%{transform:rotate(45deg) translate(0,0)} 50%{transform:rotate(45deg) translate(3px,3px)} }
 
  .animate-fadeInUp { animation: fadeInUp 0.6s ease both; }
  .delay-1 { animation-delay: 0.1s; }
  .delay-2 { animation-delay: 0.2s; }
  .delay-3 { animation-delay: 0.3s; }
  @keyframes fadeInUp { from{opacity:0;transform:translateY(20px)} to{opacity:1;transform:translateY(0)} }
 
  .btn-primary-hover:hover  { background: #7c74ff !important; transform: translateY(-2px); box-shadow: 0 4px 40px rgba(108,99,255,0.5) !important; transition: all 0.2s; }
  .btn-secondary-hover:hover{ border-color: rgba(255,255,255,0.2) !important; background: rgba(255,255,255,0.04) !important; transition: all 0.2s; }
  .step-card:hover  { border-color: rgba(108,99,255,0.3) !important; transform: translateY(-4px); transition: all 0.2s; }
  .role-card:hover  { border-color: rgba(108,99,255,0.4) !important; background: rgba(108,99,255,0.05) !important; transform: translateY(-3px); transition: all 0.2s; }
  .feature-card:hover { border-color: rgba(108,99,255,0.3) !important; transition: all 0.2s; }
`;